version: '2'
services:
  artifactory:
        build: artifactory/build/.
        container_name: art
        ports:
            - "8081:8081"


  jenkins:
        build: jenkins/build/.
        container_name: jenkins
        user: jenkins
        volumes:
            - ~/data/jenkins:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - ~/.ssh:/root/.ssh
            - ~/.ssh:ssh/var/jenkins_home/.ssh

        environment:
            JENKINS_HOST_HOME: "/data/jenkins"
        ports:
            - "8080:8080"
            - "5000:5000"
            - "50000:50000"
        links:
            - artifactory:artifactory

            
